package com.my_project.thecatapiproject.ui.animate

import android.os.Bundle
import android.widget.LinearLayout
import androidx.appcompat.app.AppCompatActivity
import androidx.recyclerview.widget.DividerItemDecoration
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.my_project.thecatapiproject.R
import kotlinx.android.synthetic.main.activity_animation.*

class AnimationActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_animation)
        init()
    }

    private fun init(){
        val aAdapter = AnimateSampleAdapter()

        animateRecyclerView.apply {
            layoutManager = LinearLayoutManager(this@AnimationActivity, RecyclerView.VERTICAL, false)
                        addItemDecoration(DividerItemDecoration(this@AnimationActivity, LinearLayout.VERTICAL))
                        adapter = aAdapter
        }

        aAdapter.swapItems(listOf(
            AnimateEntity("Name-1","https://cdn2.thecatapi.com/images/gd.jpg","Google released the first beta of Android 10 under the preliminary name \"Android Q\" on March 13, 2019, exclusively on their Pixel phones, including the first-generation Pixel and Pixel XL devices where support was extended due to popular demand.[3] Having been guaranteed updates only up to October 2018, the first-generation Pixel and Pixel XL devices received version updates to Android 10. The Pixel 2 and Pixel 2 XL were included, after being granted an extended warranty period which guaranteed Android version updates for them for at least 3 years from when they were first available on the Google Store.[4][5] A total of six beta or release-candidate versions were released before the final release.[6][7] "),
            AnimateEntity("Name-2","https://cdn2.thecatapi.com/images/pc.jpg","Google released the first beta of Android 10 under the preliminary name \"Android Q\" on March 13, 2019, exclusively on their Pixel phones, including the first-generation Pixel and Pixel XL devices where support was extended due to popular demand.[3] Having been guaranteed updates only up to October 2018, the first-generation Pixel and Pixel XL devices received version updates to Android 10. The Pixel 2 and Pixel 2 XL were included, after being granted an extended warranty period which guaranteed Android version updates for them for at least 3 years from when they were first available on the Google Store.[4][5] A total of six beta or release-candidate versions were released before the final release.[6][7] "),
            AnimateEntity("Name-3","https://cdn2.thecatapi.com/images/1he.jpg","Google released the first beta of Android 10 under the preliminary name \"Android Q\" on March 13, 2019, exclusively on their Pixel phones, including the first-generation Pixel and Pixel XL devices where support was extended due to popular demand.[3] Having been guaranteed updates only up to October 2018, the first-generation Pixel and Pixel XL devices received version updates to Android 10. The Pixel 2 and Pixel 2 XL were included, after being granted an extended warranty period which guaranteed Android version updates for them for at least 3 years from when they were first available on the Google Store.[4][5] A total of six beta or release-candidate versions were released before the final release.[6][7] "),
            AnimateEntity("Name-4","https://cdn2.thecatapi.com/images/1mh.jpg","Google released the first beta of Android 10 under the preliminary name \"Android Q\" on March 13, 2019, exclusively on their Pixel phones, including the first-generation Pixel and Pixel XL devices where support was extended due to popular demand.[3] Having been guaranteed updates only up to October 2018, the first-generation Pixel and Pixel XL devices received version updates to Android 10. The Pixel 2 and Pixel 2 XL were included, after being granted an extended warranty period which guaranteed Android version updates for them for at least 3 years from when they were first available on the Google Store.[4][5] A total of six beta or release-candidate versions were released before the final release.[6][7] "),
            AnimateEntity("Name-5","https://cdn2.thecatapi.com/images/1v4.jpg","Google released the first beta of Android 10 under the preliminary name \"Android Q\" on March 13, 2019, exclusively on their Pixel phones, including the first-generation Pixel and Pixel XL devices where support was extended due to popular demand.[3] Having been guaranteed updates only up to October 2018, the first-generation Pixel and Pixel XL devices received version updates to Android 10. The Pixel 2 and Pixel 2 XL were included, after being granted an extended warranty period which guaranteed Android version updates for them for at least 3 years from when they were first available on the Google Store.[4][5] A total of six beta or release-candidate versions were released before the final release.[6][7] "),
            AnimateEntity("Name-6","https://cdn2.thecatapi.com/images/2og.jpg","Google released the first beta of Android 10 under the preliminary name \"Android Q\" on March 13, 2019, exclusively on their Pixel phones, including the first-generation Pixel and Pixel XL devices where support was extended due to popular demand.[3] Having been guaranteed updates only up to October 2018, the first-generation Pixel and Pixel XL devices received version updates to Android 10. The Pixel 2 and Pixel 2 XL were included, after being granted an extended warranty period which guaranteed Android version updates for them for at least 3 years from when they were first available on the Google Store.[4][5] A total of six beta or release-candidate versions were released before the final release.[6][7] "),
            AnimateEntity("Name-7","https://cdn2.thecatapi.com/images/2so.jpg","Google released the first beta of Android 10 under the preliminary name \"Android Q\" on March 13, 2019, exclusively on their Pixel phones, including the first-generation Pixel and Pixel XL devices where support was extended due to popular demand.[3] Having been guaranteed updates only up to October 2018, the first-generation Pixel and Pixel XL devices received version updates to Android 10. The Pixel 2 and Pixel 2 XL were included, after being granted an extended warranty period which guaranteed Android version updates for them for at least 3 years from when they were first available on the Google Store.[4][5] A total of six beta or release-candidate versions were released before the final release.[6][7] "),
            AnimateEntity("Name-8","https://cdn2.thecatapi.com/images/585.jpg","Google released the first beta of Android 10 under the preliminary name \"Android Q\" on March 13, 2019, exclusively on their Pixel phones, including the first-generation Pixel and Pixel XL devices where support was extended due to popular demand.[3] Having been guaranteed updates only up to October 2018, the first-generation Pixel and Pixel XL devices received version updates to Android 10. The Pixel 2 and Pixel 2 XL were included, after being granted an extended warranty period which guaranteed Android version updates for them for at least 3 years from when they were first available on the Google Store.[4][5] A total of six beta or release-candidate versions were released before the final release.[6][7] "),
            AnimateEntity("Name-9","https://cdn2.thecatapi.com/images/5mu.jpg","Google released the first beta of Android 10 under the preliminary name \"Android Q\" on March 13, 2019, exclusively on their Pixel phones, including the first-generation Pixel and Pixel XL devices where support was extended due to popular demand.[3] Having been guaranteed updates only up to October 2018, the first-generation Pixel and Pixel XL devices received version updates to Android 10. The Pixel 2 and Pixel 2 XL were included, after being granted an extended warranty period which guaranteed Android version updates for them for at least 3 years from when they were first available on the Google Store.[4][5] A total of six beta or release-candidate versions were released before the final release.[6][7] "),
            AnimateEntity("Name-10","https://cdn2.thecatapi.com/images/70j.jpg","Google released the first beta of Android 10 under the preliminary name \"Android Q\" on March 13, 2019, exclusively on their Pixel phones, including the first-generation Pixel and Pixel XL devices where support was extended due to popular demand.[3] Having been guaranteed updates only up to October 2018, the first-generation Pixel and Pixel XL devices received version updates to Android 10. The Pixel 2 and Pixel 2 XL were included, after being granted an extended warranty period which guaranteed Android version updates for them for at least 3 years from when they were first available on the Google Store.[4][5] A total of six beta or release-candidate versions were released before the final release.[6][7] "),
            AnimateEntity("Name-11","https://cdn2.thecatapi.com/images/8i0.jpg","Google released the first beta of Android 10 under the preliminary name \"Android Q\" on March 13, 2019, exclusively on their Pixel phones, including the first-generation Pixel and Pixel XL devices where support was extended due to popular demand.[3] Having been guaranteed updates only up to October 2018, the first-generation Pixel and Pixel XL devices received version updates to Android 10. The Pixel 2 and Pixel 2 XL were included, after being granted an extended warranty period which guaranteed Android version updates for them for at least 3 years from when they were first available on the Google Store.[4][5] A total of six beta or release-candidate versions were released before the final release.[6][7] ")
        ))

    }



}
